# Generated by Django 3.2.8 on 2021-10-27 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=15, verbose_name='Марка автомобиля')),
                ('vin', models.CharField(max_length=17, verbose_name='Вин номер автомобиля')),
                ('description', models.TextField(max_length=500, verbose_name='Описание автомобиля')),
                ('date', models.TextField(verbose_name='Дата осмотра автомобиля')),
                ('image', models.ImageField(blank=True, default='images/1.png', help_text='Прикрепите изображения (необязательно)', upload_to='images', verbose_name='Фотография')),
            ],
        ),
    ]
