# Generated by Django 3.2.8 on 2021-10-16 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=15, verbose_name='Марка автомобиля')),
                ('vin', models.TextField(verbose_name='Вин номер автомобиля')),
                ('description', models.CharField(max_length=500, verbose_name='Описание автомобиля')),
                ('date', models.DateField(verbose_name='Дата осмотра автомобиля')),
            ],
        ),
    ]
