# Generated by Django 3.2.8 on 2021-11-23 21:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avto',
            name='date',
            field=models.DateField(verbose_name='Дата осмотра автомобиля'),
        ),
        migrations.AlterField(
            model_name='avto',
            name='description',
            field=models.TextField(blank=True, max_length=500, verbose_name='Описание автомобиля'),
        ),
        migrations.AlterField(
            model_name='avto',
            name='image',
            field=models.ImageField(blank=True, default='images/1.png', upload_to='images', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='avto',
            name='vin',
            field=models.CharField(max_length=17, unique=True, validators=[django.core.validators.MinLengthValidator(17)], verbose_name='Вин номер автомобиля'),
        ),
    ]
