# Generated by Django 3.2.8 on 2021-10-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avto',
            name='date',
            field=models.TextField(verbose_name='Дата осмотра автомобиля'),
        ),
        migrations.AlterField(
            model_name='avto',
            name='description',
            field=models.TextField(max_length=500, verbose_name='Описание автомобиля'),
        ),
        migrations.AlterField(
            model_name='avto',
            name='vin',
            field=models.CharField(max_length=17, verbose_name='Вин номер автомобиля'),
        ),
    ]
