# Generated by Django 3.2.8 on 2021-10-25 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211017_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='avto',
            name='image',
            field=models.ImageField(default=1, upload_to='images', verbose_name='Фотография'),
            preserve_default=False,
        ),
    ]
