# Generated by Django 3.2.8 on 2021-10-25 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_avto_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avto',
            name='image',
            field=models.ImageField(blank=True, default='images/1.png', help_text='Прикрепите изображения (необязательно)', upload_to='images', verbose_name='Фотография'),
        ),
    ]
